version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "@database"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes:
      - /home/peidrao/Docker
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge